// Generates docs/plans/2026-09-30-email-flow-content.sql from the flow
// templates (src/lib/email/flow-templates.ts), so the live `flows` rows and the
// gallery "Use template" stay identical. Run after any copy change:
//   npx tsx scripts/gen-email-flow-sql.ts
// NOT a migration: the output is pasted by hand in the Supabase SQL editor
// after the engine from the same batch is deployed (see the file header).
import { writeFileSync } from "node:fs";
import { FLOW_TEMPLATES, type FlowTemplate } from "@/lib/email/flow-templates";

const OUT = "docs/plans/2026-09-30-email-flow-content.sql";

/** The live, ACTIVE abandoned-cart row (updated in place, keeps its enrolments). */
const LIVE_CART_FLOW_ID = "9a027102-4805-463c-880f-a7ed296af414";
/**
 * Order-placed DRAFTS made in the Automations page on 2026-09-30. They overlap
 * Post-purchase / Review / Replenishment below; having both switched on would
 * email a customer twice, so section B.0 removes them (drafts, never sent).
 */
const OVERLAPPING_DRAFT_IDS = [
  "52f98eb1-c65a-4203-aa24-674ef912a2ab", // Welcome to the PROMUNCH family
  "e0a8a156-8136-4f7f-9f8a-60d436387f1c", // Post-purchase: enjoy + review
  "ba7ca8b3-9bfe-4120-a835-b0d31d607ae2", // Replenishment: time to restock
];

const lit = (s: string) => `'${s.replace(/'/g, "''")}'`;
const json = (v: unknown) => {
  const body = JSON.stringify(v);
  if (body.includes("$j$")) throw new Error("dollar-quote tag clash");
  return `$j$${body}$j$::jsonb`;
};

function delayLabel(h: number): string {
  if (h < 1) return `+${Math.round(h * 60)} min`;
  if (h < 48) return `+${h}h`;
  return `+day ${Math.round((h / 24) * 10) / 10}`;
}

function outline(t: FlowTemplate): string {
  return t.steps
    .map((s, i) => {
      const offer = s.coupon ? `${s.coupon.percent_off}% unique (${s.coupon.prefix ?? "PM"})` : "no code";
      const from = s.from_name ? `, from "${s.from_name}"` : "";
      return `--   ${String(i + 1).padStart(2)}. ${delayLabel(s.delay_hours).padEnd(11)} ${offer.padEnd(26)} "${s.subject}"${from}`;
    })
    .join("\n");
}

const cart = FLOW_TEMPLATES.find((t) => t.key === "abandoned_cart");
if (!cart) throw new Error("abandoned_cart template missing");
const others = FLOW_TEMPLATES.filter((t) => t.key !== "abandoned_cart");
const emailCount = FLOW_TEMPLATES.reduce((n, t) => n + t.steps.length, 0);

const parts: string[] = [];
parts.push(`-- ============================================================
-- EMAIL FLOW CONTENT v5 (generated ${new Date().toISOString().slice(0, 10)}). NOT A MIGRATION.
-- Owner-approved copy (all ${emailCount} emails, reviewed one by one on 2026-09-30/10-01).
-- GENERATED by scripts/gen-email-flow-sql.ts from src/lib/email/flow-templates.ts.
-- Do not hand-edit: change the templates and regenerate.
--
-- Offers: 15% everywhere except win-back (20%). Every offer is a unique
-- single-use Shopify code per enrolment (coupon_code is "" on purpose: when
-- minting fails the engine DEFERS the step, it never sends without a code).
-- Founder emails come "from Parth from PROMUNCH" in the founder-letter layout.
--
-- ORDER OF OPERATIONS (do not skip):
--   0. Shopify app must have the write_discounts scope, or every offer email
--      defers forever (safe, but nothing goes out).
--   1. DEPLOY the engine from the same batch first: vercel --prod, the edge
--      functions (shopify-wa, shopify-status, shopify-webhook, wa-jobs-tick),
--      and migrations 20260930100000, 20260930110000, 20260930120500,
--      20260930130000, 20260930140000 applied. On the OLD engine these rows
--      would render {{coupon_code}} empty.
--   2. Section A UPDATES the live, ACTIVE abandoned-cart flow: it takes effect
--      on the next tick. Take the A.0 snapshot first.
--   3. Section B.0 removes the 3 overlapping order_placed drafts, then B inserts
--      the other ${others.length} flows as status='draft'. Nothing in B sends until someone
--      switches a flow on in Email Studio > Automations.
-- ============================================================

begin;`);

parts.push(`
-- ============================================================
-- A. ${cart.name.toUpperCase()} (live row UPDATE)
${outline(cart)}
-- ============================================================

-- A.0 snapshot (restore: update flows f set name=b.name, description=b.description,
--     trigger_config=b.trigger_config, steps=b.steps from flows_backup_20261001 b where f.id=b.id;)
create table if not exists flows_backup_20261001 as
  select * from flows where id = ${lit(LIVE_CART_FLOW_ID)};

update flows set
  name = ${lit(cart.name)},
  description = ${lit(cart.description)},
  trigger_config = ${json(cart.trigger_config)},
  steps = ${json(cart.steps)},
  updated_at = now()
where id = ${lit(LIVE_CART_FLOW_ID)} and trigger_type = ${lit(cart.trigger_type)};`);

parts.push(`
-- ============================================================
-- B.0 remove the overlapping order_placed drafts (never active, no sends)
-- ============================================================
delete from flows
where id in (${OVERLAPPING_DRAFT_IDS.map(lit).join(", ")})
  and status = 'draft'
  and not exists (select 1 from flow_enrollments e where e.flow_id = flows.id);`);

for (const t of others) {
  parts.push(`
-- ============================================================
-- B. ${t.name.toUpperCase()} (${t.trigger_type}, draft)
--   ${t.description}
${outline(t)}
-- ============================================================
insert into flows (name, description, trigger_type, trigger_config, steps, status)
select ${lit(t.name)}, ${lit(t.description)}, ${lit(t.trigger_type)}, ${json(t.trigger_config)}, ${json(t.steps)}, 'draft'
where not exists (select 1 from flows where name = ${lit(t.name)} and trigger_type = ${lit(t.trigger_type)});`);
}

parts.push(`
commit;

-- Check: expect 1 active (abandoned cart) + ${others.length} drafts from this file.
-- select status, trigger_type, name, jsonb_array_length(steps) as emails from flows order by created_at;
`);

writeFileSync(OUT, parts.join("\n"));
console.log(`wrote ${OUT}: ${FLOW_TEMPLATES.length} flows, ${emailCount} emails`);
